version: "3.8"

services:

  backend:
    image: akashgoudru/backend-app:latest
    container_name: backend_staging
    ports:
      - "5001:5000"
    environment:
      DB_HOST: db
      DB_NAME: staging_db
      DB_USER: staging_user
      DB_PASSWORD: staging_pass
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_staging
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_staging
    environment:
      POSTGRES_DB: staging_db
      POSTGRES_USER: staging_user
      POSTGRES_PASSWORD: staging_pass
    volumes:
      - staging_db_data:/var/lib/postgresql/data

volumes:
  staging_db_data:
